Sakanatcom/Models/MasterContactUsInformation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

#nullable disable

namespace Sakanatcom.Models
{
    public partial class MasterContactUsInformation : BaseEntity
    {
        [DisplayName("Id")]
        public int MasterContactUsInformationId { get; set; }
        [Required(ErrorMessage = "Description Is Required")]
        [DisplayName("Description")]
        public string MasterContactUsInformationDesc { get; set; }
        [Required(ErrorMessage = "Icon Is Required")]
        [DisplayName("Icon")]
        public string MasterContactUsInformationIcon { get; set; }
        [Required(ErrorMessage = "Redirect Is Required")]
        [DisplayName("Redirect")]
        public string MasterContactUsInformationRedirect { get; set; }
    }
}

Sakanatcom/ViewModels/MasterContactUsInformationViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.AspNetCore.Http;

namespace Sakanatcom.ViewModels
{
    public class MasterContactUsInformationViewModel : BaseEntity
    {
        [DisplayName("Id")]
        public int MasterContactUsInformationId { get; set; }
        [Required(ErrorMessage = "Description Is Required")]
        [DisplayName("Description")]
        public string MasterContactUsInformationDesc { get; set; }
        [Required(ErrorMessage = "Icon Is Required")]
        [DisplayName("Icon")]
        public string MasterContactUsInformationIcon { get; set; }
        [Required(ErrorMessage = "Redirect Is Required")]
        [DisplayName("Redirect")]
        public string MasterContactUsInformationRedirect { get; set; }
    }
}

Sakanatcom/Areas/Admin/Controllers/MasterContactUsInformationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sakanatcom.Models;
using Sakanatcom.Models.Repositories;
using Sakanatcom.ViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Security.Claims;

namespace Sakanatcom.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MasterContactUsInformationController : Controller
    {
        public IRepository<MasterContactUsInformation> MasterContactUsInformationRepository { get; }

        public MasterContactUsInformationController(
            IRepository<MasterContactUsInformation> MasterContactUsInformationRepository)
        {
            this.MasterContactUsInformationRepository = MasterContactUsInformationRepository;
        }

        public ActionResult Index()
        {
            IList<MasterContactUsInformation> dataList = MasterContactUsInformationRepository.View();
            IList<MasterContactUsInformationViewModel> dataViewModelList = new List<MasterContactUsInformationViewModel>();
            foreach (var data in dataList)
            {
                MasterContactUsInformationViewModel dataViewModel = new MasterContactUsInformationViewModel()
                {
                    MasterContactUsInformationId = data.MasterContactUsInformationId,
                    MasterContactUsInformationDesc = data.MasterContactUsInformationDesc,
                    MasterContactUsInformationIcon = data.MasterContactUsInformationIcon,
                    MasterContactUsInformationRedirect = data.MasterContactUsInformationRedirect,
                    IsActive = data.IsActive,
                };
                dataViewModelList.Add(dataViewModel);
            }
            return View(dataViewModelList);
        }

        public ActionResult Active(int id)
        {
            MasterContactUsInformationRepository.Active(id, new MasterContactUsInformation()
            {
                EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                EditDate = DateTime.UtcNow
            });
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Create()
        {
            MasterContactUsInformationViewModel dataViewModel = new MasterContactUsInformationViewModel();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterContactUsInformationViewModel dataViewModel)
        {
            try
            {
                MasterContactUsInformation data = new MasterContactUsInformation()
                {
                    MasterContactUsInformationDesc = dataViewModel.MasterContactUsInformationDesc,
                    MasterContactUsInformationIcon = dataViewModel.MasterContactUsInformationIcon,
                    MasterContactUsInformationRedirect = dataViewModel.MasterContactUsInformationRedirect,
                    IsActive = true,
                    IsDelete = false,
                    CreateUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    CreateDate = DateTime.UtcNow
                };
                MasterContactUsInformationRepository.Add(data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            MasterContactUsInformation data = MasterContactUsInformationRepository.Find(id);
            MasterContactUsInformationViewModel dataViewModel = new MasterContactUsInformationViewModel()
            {
                MasterContactUsInformationId = data.MasterContactUsInformationId,
                MasterContactUsInformationDesc = data.MasterContactUsInformationDesc,
                MasterContactUsInformationIcon = data.MasterContactUsInformationIcon,
                MasterContactUsInformationRedirect = data.MasterContactUsInformationRedirect,
            };
            return View(dataViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MasterContactUsInformationViewModel dataViewModel)
        {
            try
            {
                MasterContactUsInformation data = MasterContactUsInformationRepository.Find(id);
                data.EditDate = DateTime.Now;
                data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                data.MasterContactUsInformationDesc = dataViewModel.MasterContactUsInformationDesc;
                data.MasterContactUsInformationIcon = dataViewModel.MasterContactUsInformationIcon;
                data.MasterContactUsInformationRedirect = dataViewModel.MasterContactUsInformationRedirect;
                MasterContactUsInformationRepository.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            MasterContactUsInformationRepository.Delete(id, new MasterContactUsInformation()
            {
                EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                EditDate = DateTime.UtcNow
            });
            return RedirectToAction(nameof(Index));
        }
    }
}

Sakanatcom/Areas/Admin/Views/MasterContactUsInformation/Create.cshtml
@model Sakanatcom.ViewModels.MasterContactUsInformationViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterContactUsInformation">ContactUs Information</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form asp-action="Create">
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterContactUsInformationId" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterContactUsInformationId" value="0" readonly class="form-control" />
                                        <span asp-validation-for="MasterContactUsInformationId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterContactUsInformationRedirect" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterContactUsInformationRedirect" class="form-control" />
                                        <span asp-validation-for="MasterContactUsInformationRedirect" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterContactUsInformationIcon" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterContactUsInformationIcon" class="form-control" />
                                        <span asp-validation-for="MasterContactUsInformationIcon" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterContactUsInformationDesc" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <textarea asp-for="MasterContactUsInformationDesc" class="form-control">
                                 </textarea>
                                        <span asp-validation-for="MasterContactUsInformationDesc" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 d-inline-flex justify-content-end">
                                <a asp-action="Index" class="btn btn-success btn-backtolist">Back to List</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Sakanatcom/Areas/Admin/Views/MasterContactUsInformation/Edit.cshtml
@model Sakanatcom.ViewModels.MasterContactUsInformationViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterContactUsInformation">ContactUs Information</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form asp-action="Edit" enctype="multipart/form-data">
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterContactUsInformationId" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterContactUsInformationId" value="0" readonly class="form-control" />
                                        <span asp-validation-for="MasterContactUsInformationId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterContactUsInformationRedirect" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterContactUsInformationRedirect" class="form-control" />
                                        <span asp-validation-for="MasterContactUsInformationRedirect" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterContactUsInformationIcon" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterContactUsInformationIcon" class="form-control" />
                                        <span asp-validation-for="MasterContactUsInformationIcon" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterContactUsInformationDesc" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <textarea asp-for="MasterContactUsInformationDesc" class="form-control">
                                 </textarea>
                                        <span asp-validation-for="MasterContactUsInformationDesc" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 d-inline-flex justify-content-end">
                                <a asp-action="Index" class="btn btn-success btn-backtolist">Back to List</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Sakanatcom/Areas/Admin/Views/MasterContactUsInformation/Index.cshtml
@model IEnumerable<Sakanatcom.ViewModels.MasterContactUsInformationViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">ContactUs Information</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-end">
                        <a asp-action="Create" class="btn btn-primary">Create New +</a>
                    </h5>
                    <table class="table datatable index-table text-break">
                        <thead>
                            <tr class="bg-dark text-white">
                                <th>
                                    @Html.DisplayNameFor(model => model.MasterContactUsInformationId)
                                </th>
                                <th class="w-25">
                                    @Html.DisplayNameFor(model => model.MasterContactUsInformationDesc)
                                </th>
                                <th class="w-25">
                                    @Html.DisplayNameFor(model => model.MasterContactUsInformationRedirect)
                                </th>
                                 <th class="text-center">
                                    Operations
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-dark-light">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="align-middle">
                                        @Html.DisplayFor(modelItem => item.MasterContactUsInformationId)
                                    </td>
                                    <td class="align-middle w-25">
                                        @Html.DisplayFor(modelItem => item.MasterContactUsInformationDesc)
                                    </td>
                                    <td class="align-middle w-25">
                                        @Html.DisplayFor(modelItem => item.MasterContactUsInformationRedirect)
                                    </td>
                                    <td class="align-middle text-center">
                                        <a asp-action="Edit" asp-route-id="@item.MasterContactUsInformationId">
                                            <i class="bx bxs-edit text-secondary h5"></i>
                                        </a>
                                        <a href="" data-bs-toggle="modal" data-bs-target="#deleteModal" id="btn-delete"
                                       data-path="@Url.ActionLink("Delete","MasterContactUsInformation",new {id= item.MasterContactUsInformationId})">
                                            <i class="bx bxs-trash text-danger h5"></i>
                                        </a>
                                        @if (item.IsActive)
                                        {
                                            <a asp-action="Active" asp-route-id="@item.MasterContactUsInformationId">
                                                <i class="ri-eye-fill text-success h5"></i>
                                            </a>
                                        }
                                        else
                                        {
                                            <a asp-action="Active" asp-route-id="@item.MasterContactUsInformationId">
                                                <i class="ri-eye-close-fill text-danger h5"></i>
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>