Sakanatcom/Models/MasterWorkingHour.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Sakanatcom.Models
{
    public partial class MasterWorkingHour : BaseEntity
    {
        [DisplayName("Id")]
        public int MasterWorkingHourId { get; set; }
        [Required(ErrorMessage = "Day Name Is Required")]
        [DisplayName("Day Name")]
        public string MasterWorkingHourName { get; set; }
        [Required(ErrorMessage = "Working Time Is Required")]
        [DisplayName("Working Time")]
        public string MasterWorkingHourTimeFormTo { get; set; }
    }
}

Sakanatcom/ViewModels/MasterWorkingHourViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System;

namespace Sakanatcom.ViewModels
{
    public class MasterWorkingHourViewModel : BaseEntity
    {
        [DisplayName("Id")]
        public int MasterWorkingHourId { get; set; }
        [Required(ErrorMessage = "Day Name Is Required")]
        [DisplayName("Day Name")]
        public string MasterWorkingHourName { get; set; }
        [Required(ErrorMessage = "Working Time Is Required")]
        [DisplayName("Working Time")]
        public string MasterWorkingHourTimeFormTo { get; set; }
    }
}

Sakanatcom/Areas/Admin/Controllers/MasterWorkingHourController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;
using Sakanatcom.Models;
using Sakanatcom.Models.Repositories;
using Sakanatcom.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Claims;

namespace Sakanatcom.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MasterWorkingHourController : Controller
    {
        public IRepository<MasterWorkingHour> MasterWorkingHourRepository { get; }

        public MasterWorkingHourController(IRepository<MasterWorkingHour> MasterWorkingHourRepository)
        {
            this.MasterWorkingHourRepository = MasterWorkingHourRepository;
        }
        public ActionResult Index()
        {
            IList<MasterWorkingHour> dataList = MasterWorkingHourRepository.View();
            IList<MasterWorkingHourViewModel> dataViewModelList = new List<MasterWorkingHourViewModel>();
            foreach (var data in dataList)
            {
                MasterWorkingHourViewModel dataViewModel = new MasterWorkingHourViewModel()
                {
                    MasterWorkingHourId = data.MasterWorkingHourId,
                    MasterWorkingHourName = data.MasterWorkingHourName,
                    MasterWorkingHourTimeFormTo = data.MasterWorkingHourTimeFormTo,
                    IsActive = data.IsActive,
                };
                dataViewModelList.Add(dataViewModel);
            }
            return View(dataViewModelList);
        }

        public ActionResult Active(int id)
        {
            MasterWorkingHourRepository.Active(id, new MasterWorkingHour()
            {
                EditDate = DateTime.UtcNow,
                EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier)
            });
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Create()
        {
            MasterWorkingHourViewModel data = new MasterWorkingHourViewModel();
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterWorkingHourViewModel dataViewModel)
        {
            try
            {
                MasterWorkingHour data = new MasterWorkingHour()
                {
                    MasterWorkingHourName = dataViewModel.MasterWorkingHourName,
                    MasterWorkingHourTimeFormTo = dataViewModel.MasterWorkingHourTimeFormTo,
                    CreateDate = DateTime.UtcNow,
                    CreateUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    IsActive = true,
                    IsDelete = false
                };
                MasterWorkingHourRepository.Add(data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            MasterWorkingHour data = MasterWorkingHourRepository.Find(id);
            MasterWorkingHourViewModel dataViewModel = new MasterWorkingHourViewModel()
            {
                MasterWorkingHourId = data.MasterWorkingHourId,
                MasterWorkingHourName = data.MasterWorkingHourName,
                MasterWorkingHourTimeFormTo = data.MasterWorkingHourTimeFormTo,
            };
            return View(dataViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MasterWorkingHour dataViewModel)
        {
            try
            {
                MasterWorkingHour data = MasterWorkingHourRepository.Find(id);
                data.MasterWorkingHourName = dataViewModel.MasterWorkingHourName;
                data.MasterWorkingHourTimeFormTo = dataViewModel.MasterWorkingHourTimeFormTo;
                data.EditDate = DateTime.UtcNow;
                data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                MasterWorkingHourRepository.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            MasterWorkingHourRepository.Delete(id, new MasterWorkingHour()
            {
                EditDate = DateTime.UtcNow,
                EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier)
            });
            return RedirectToAction(nameof(Index));
        }
    }
}

Sakanatcom/Areas/Admin/Views/MasterWorkingHour/Create.cshtml
@model Sakanatcom.ViewModels.MasterWorkingHourViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterWorkingHour">Working Hour</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form asp-action="Create">
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterWorkingHourId" class="col-sm-6 col-form-label"></label>
                                    <div class="col-sm-6">
                                        <input asp-for="MasterWorkingHourId" readonly class="form-control" />
                                        <span asp-validation-for="MasterWorkingHourId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterWorkingHourName" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterWorkingHourName" class="form-control" />
                                        <span asp-validation-for="MasterWorkingHourName" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterWorkingHourTimeFormTo" class="col-sm-6 col-form-label"></label>
                                    <div class="col-sm-6">
                                        <input asp-for="MasterWorkingHourTimeFormTo" class="form-control" />
                                        <span asp-validation-for="MasterWorkingHourTimeFormTo" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 d-inline-flex justify-content-end">
                                <a asp-action="Index" class="btn btn-success btn-backtolist">Back to List</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Sakanatcom/Areas/Admin/Views/MasterWorkingHour/Edit.cshtml
@model Sakanatcom.ViewModels.MasterWorkingHourViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterWorkingHour">Working Hour</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form asp-action="Edit">
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterWorkingHourId" class="col-sm-6 col-form-label"></label>
                                    <div class="col-sm-6">
                                        <input asp-for="MasterWorkingHourId" readonly class="form-control" />
                                        <span asp-validation-for="MasterWorkingHourId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterWorkingHourName" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterWorkingHourName" class="form-control" />
                                        <span asp-validation-for="MasterWorkingHourName" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterWorkingHourTimeFormTo" class="col-sm-6 col-form-label"></label>
                                    <div class="col-sm-6">
                                        <input asp-for="MasterWorkingHourTimeFormTo" class="form-control" />
                                        <span asp-validation-for="MasterWorkingHourTimeFormTo" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 d-inline-flex justify-content-end">
                                <a asp-action="Index" class="btn btn-success btn-backtolist">Back to List</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Sakanatcom/Areas/Admin/Views/MasterWorkingHour/Index.cshtml
@model IEnumerable<Sakanatcom.ViewModels.MasterWorkingHourViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">Working Hour</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-end">
                        <a asp-action="Create" class="btn btn-primary">Create New +</a>
                    </h5>
                    <table class="table datatable index-table text-break">
                        <thead>
                            <tr class="bg-dark text-white">
                                <th>
                                    @Html.DisplayNameFor(model => model.MasterWorkingHourId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MasterWorkingHourName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MasterWorkingHourTimeFormTo)
                                </th>
                                <th class="text-center">
                                    Operations
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-dark-light">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="align-middle">
                                        @Html.DisplayFor(modelItem => item.MasterWorkingHourId)
                                    </td>
                                    <td class="align-middle">
                                        @Html.DisplayFor(modelItem => item.MasterWorkingHourName)
                                    </td>
                                    <td class="align-middle">
                                        @Html.DisplayFor(modelItem => item.MasterWorkingHourTimeFormTo)
                                    </td>
                                    <td class="align-middle text-center">
                                        <a asp-action="Edit" asp-route-id="@item.MasterWorkingHourId">
                                            <i class="bx bxs-edit text-secondary h5"></i>
                                        </a>
                                        <a href="" data-bs-toggle="modal" data-bs-target="#deleteModal" id="btn-delete"
                                       data-path="@Url.ActionLink("Delete","MasterWorkingHour",new {id= item.MasterWorkingHourId})">
                                            <i class="bx bxs-trash text-danger h5"></i>
                                        </a>
                                        @if (item.IsActive)
                                        {
                                            <a asp-action="Active" asp-route-id="@item.MasterWorkingHourId">
                                                <i class="ri-eye-fill text-success h5"></i>
                                            </a>
                                        }
                                        else
                                        {
                                            <a asp-action="Active" asp-route-id="@item.MasterWorkingHourId">
                                                <i class="ri-eye-close-fill text-danger h5"></i>
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>