Sakanatcom/Models/MasterPartner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Sakanatcom.Models
{
    public partial class MasterPartner : BaseEntity
    {
        [DisplayName("Id")]
        public int MasterPartnerId { get; set; }
        [Required(ErrorMessage = "Your Name Name Is Required")]
        [DisplayName("Name")]
        public string MasterPartnerName { get; set; }
        [DisplayName("Profile picture")]
        public string MasterPartnerLogoImageUrl { get; set; }
        [Required(ErrorMessage = "Discription Required")]
        [DisplayName("Discription")]
        public string MasterPartnerWebsiteUrl { get; set; }
    }
}

Sakanatcom/ViewModels/MasterPartnerViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.AspNetCore.Http;

namespace Sakanatcom.ViewModels
{
    public class MasterPartnerViewModel : BaseEntity
    {
        [DisplayName("Id")]
        public int MasterPartnerId { get; set; }
        [Required(ErrorMessage = "Your Name Name Is Required")]
        [DisplayName("Name")]
        public string MasterPartnerName { get; set; }
        [DisplayName("Profile picture")]
        public string MasterPartnerLogoImageUrl { get; set; }
        [Required(ErrorMessage = "Discription Required")]
        [DisplayName("Discription")]
        public string MasterPartnerWebsiteUrl { get; set; }
        [DisplayName("Upload Logo")]
        public IFormFile UploadLogo { get; set; }
    }
}

Sakanatcom/Areas/Admin/Controllers/MasterPartnerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sakanatcom.Models;
using Sakanatcom.Models.Repositories;
using Sakanatcom.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;

namespace Sakanatcom.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MasterPartnerController : Controller
    {
        public IRepository<MasterPartner> MasterPartnerRepository { get; }
        public IHostingEnvironment HostingEnvironment { get; }

        public MasterPartnerController(
            IRepository<MasterPartner> MasterPartnerRepository,
            IHostingEnvironment HostingEnvironment)
        {
            this.MasterPartnerRepository = MasterPartnerRepository;
            this.HostingEnvironment = HostingEnvironment;
        }
        public ActionResult Index()
        {
            IList<MasterPartner> dataList = MasterPartnerRepository.View();
            IList<MasterPartnerViewModel> dataViewModelList = new List<MasterPartnerViewModel>();
            foreach (var data in dataList)
            {
                MasterPartnerViewModel dataViewModel = new MasterPartnerViewModel()
                {
                    MasterPartnerId = data.MasterPartnerId,
                    MasterPartnerName = data.MasterPartnerName,
                    MasterPartnerLogoImageUrl = data.MasterPartnerLogoImageUrl,
                    MasterPartnerWebsiteUrl = data.MasterPartnerWebsiteUrl,
                    IsActive = data.IsActive,
                };
                dataViewModelList.Add(dataViewModel);
            }
            return View(dataViewModelList);
        }

        public ActionResult Active(int id)
        {
            MasterPartnerRepository.Active(id, new MasterPartner()
            {
                EditDate = DateTime.UtcNow,
                EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier)
            });
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Create()
        {
            MasterPartnerViewModel dataViewModel = new MasterPartnerViewModel();
            return View(dataViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterPartnerViewModel dataViewModel)
        {
            try
            {
                if (MasterPartnerRepository.View().Where(data => data.MasterPartnerName.ToUpper()
                == dataViewModel.MasterPartnerName.ToUpper()).ToList().Count > 0)
                {
                    ModelState.AddModelError("", "This name is already used.");
                    return View(dataViewModel);
                }
                string imageName = "";
                if (dataViewModel.UploadLogo != null)
                {
                    string imagePath = Path.Combine(HostingEnvironment.WebRootPath, "images/partner");
                    FileInfo fileInfo = new FileInfo(dataViewModel.UploadLogo.FileName);
                    imageName = "masterPartnerLogo" + Guid.NewGuid() + fileInfo.Extension;
                    string fullPath = Path.Combine(imagePath, imageName);
                    dataViewModel.UploadLogo.CopyTo(new FileStream(fullPath, FileMode.Create));
                }
                MasterPartner data = new MasterPartner()
                {
                    MasterPartnerName = dataViewModel.MasterPartnerName,
                    MasterPartnerWebsiteUrl = dataViewModel.MasterPartnerWebsiteUrl,
                    MasterPartnerLogoImageUrl = (string.IsNullOrEmpty(imageName) ? null : imageName),
                    CreateDate = DateTime.UtcNow,
                    CreateUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    IsActive = true,
                    IsDelete = false
                };
                MasterPartnerRepository.Add(data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            MasterPartner data = MasterPartnerRepository.Find(id);
            MasterPartnerViewModel dataViewModel = new MasterPartnerViewModel()
            {
                MasterPartnerId = data.MasterPartnerId,
                MasterPartnerName = data.MasterPartnerName,
                MasterPartnerLogoImageUrl = data.MasterPartnerLogoImageUrl,
                MasterPartnerWebsiteUrl = data.MasterPartnerWebsiteUrl
            };
            return View(dataViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MasterPartnerViewModel dataViewModel)
        {
            try
            {

                MasterPartner data = MasterPartnerRepository.Find(id);
                if (MasterPartnerRepository.View().Where(data => data.MasterPartnerName.ToUpper()
                == dataViewModel.MasterPartnerName.ToUpper()).ToList().Count > 0
                && data.MasterPartnerName.ToUpper() != dataViewModel.MasterPartnerName.ToUpper())
                {
                    ModelState.AddModelError("", "This name is already used.");
                    return View(dataViewModel);
                }
                string imageName = dataViewModel.MasterPartnerLogoImageUrl;
                if (dataViewModel.UploadLogo != null)
                {
                    string imagePath = Path.Combine(HostingEnvironment.WebRootPath, "images/partner");
                    FileInfo fileInfo = new FileInfo(dataViewModel.UploadLogo.FileName);
                    imageName = "masterPartnerLogo" + Guid.NewGuid() + fileInfo.Extension;
                    string fullPath = Path.Combine(imagePath, imageName);
                    dataViewModel.UploadLogo.CopyTo(new FileStream(fullPath, FileMode.Create));
                }
                data.MasterPartnerName = dataViewModel.MasterPartnerName;
                data.MasterPartnerWebsiteUrl = dataViewModel.MasterPartnerWebsiteUrl;
                data.MasterPartnerLogoImageUrl = (string.IsNullOrEmpty(imageName) ? null : imageName);
                data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                data.EditDate = DateTime.UtcNow;
                MasterPartnerRepository.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            MasterPartnerRepository.Delete(id, new MasterPartner()
            {
                EditDate = DateTime.UtcNow,
                EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier)
            });
            return RedirectToAction(nameof(Index));
        }
    }
}

Sakanatcom/Areas/Admin/Views/MasterPartner/Create.cshtml
@model Sakanatcom.ViewModels.MasterPartnerViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterPartner">FeedBacks</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="row mb-3 d-flex justify-content-center">
                            <div class="col-sm-12 text-center">
                                <label asp-for="UploadLogo" class="col-sm-12 text-center col-form-label">
                                    <img asp-for="UploadImage" id="MasterPartnerImg" src="~/Admin/assets/img/not-found.svg" class="img img-fluid border border-2 border-dark rounded-3 p-5" width="300" />
                                </label>
                                <input asp-for="UploadLogo" hidden onchange="loadFile(event,'#MasterPartnerImg')" class="form-control" />
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label asp-for="UploadLogo" class="col-sm-12 text-center col-form-label"></label>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterPartnerId" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterPartnerId" readonly class="form-control" />
                                        <span asp-validation-for="MasterPartnerId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterPartnerName" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterPartnerName" class="form-control" />
                                        <span asp-validation-for="MasterPartnerName" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterPartnerWebsiteUrl" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterPartnerWebsiteUrl" class="form-control" />
                                        <span asp-validation-for="MasterPartnerWebsiteUrl" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 d-inline-flex justify-content-end">
                                <a asp-action="Index" class="btn btn-success btn-backtolist">Back to List</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Sakanatcom/Areas/Admin/Views/MasterPartner/Edit.cshtml
@model Sakanatcom.ViewModels.MasterPartnerViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterPartner">FeedBacks</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form asp-action="Edit" enctype="multipart/form-data">
                        <div class="row mb-3 d-flex justify-content-center">
                            <div class="col-sm-12 text-center">
                                <label asp-for="UploadLogo" class="col-sm-12 text-center col-form-label">
                                    @if (string.IsNullOrEmpty(Model.MasterPartnerLogoImageUrl))
                                    {
                                        <img asp-for="UploadImage" id="MasterPartnerImg" src="~/Admin/assets/img/not-found.svg" class="img img-fluid border border-2 border-dark rounded-3 p-5" width="300" />
                                    }
                                    else
                                    {
                                        <img asp-for="UploadImage" id="MasterPartnerImg" src="~/images/partner/@Model.MasterPartnerLogoImageUrl" class="img img-fluid border border-2 border-dark rounded-3 p-5" width="300" />
                                    }
                                </label>
                                <input asp-for="UploadLogo" hidden onchange="loadFile(event,'#MasterPartnerImg')" class="form-control" />
                                <input asp-for="MasterPartnerLogoImageUrl" hidden class="form-control" />
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label asp-for="UploadLogo" class="col-sm-12 text-center col-form-label"></label>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterPartnerId" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterPartnerId" readonly class="form-control" />
                                        <span asp-validation-for="MasterPartnerId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterPartnerName" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterPartnerName" class="form-control" />
                                        <span asp-validation-for="MasterPartnerName" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterPartnerWebsiteUrl" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterPartnerWebsiteUrl" class="form-control" />
                                        <span asp-validation-for="MasterPartnerWebsiteUrl" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 d-inline-flex justify-content-end">
                                <a asp-action="Index" class="btn btn-success btn-backtolist">Back to List</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Sakanatcom/Areas/Admin/Views/MasterPartner/Index.cshtml
@model IEnumerable<Sakanatcom.ViewModels.MasterPartnerViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">FeedBacks</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                   
                    <table class="table datatable index-table text-break">
                        <thead>
                            <tr class="bg-dark text-white">
                                <th>
                                    @Html.DisplayNameFor(model => model.MasterPartnerId)
                                </th>
                               
                                <th class="w-25">
                                    @Html.DisplayNameFor(model => model.MasterPartnerName)
                                </th>
                                <th class="w-25">
                                    @Html.DisplayNameFor(model => model.MasterPartnerWebsiteUrl)
                                </th>
                                <th class="text-center">
                                    Operations
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-dark-light">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="align-middle">
                                        @Html.DisplayFor(modelItem => item.MasterPartnerId)
                                    </td>
                                   
                                    <td class="align-middle">
                                        @Html.DisplayFor(modelItem => item.MasterPartnerName)
                                    </td>
                                    <td class="align-middle w-25">
                                        @Html.DisplayFor(modelItem => item.MasterPartnerWebsiteUrl)
                                    </td>
                                    <td class="align-middle text-center">
                                     
                                        <a href="" data-bs-toggle="modal" data-bs-target="#deleteModal" id="btn-delete"
                                       data-path="@Url.ActionLink("Delete","MasterPartner",new {id= item.MasterPartnerId})">
                                            <i class="bx bxs-trash text-danger h5"></i>
                                        </a>
                                        @if (item.IsActive)
                                        {
                                            <a asp-action="Active" asp-route-id="@item.MasterPartnerId">
                                                <i class="ri-eye-fill text-success h5"></i>
                                            </a>
                                        }
                                        else
                                        {
                                            <a asp-action="Active" asp-route-id="@item.MasterPartnerId">
                                                <i class="ri-eye-close-fill text-danger h5"></i>
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>