Sakanatcom/Models/MasterMenu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Sakanatcom.Models
{
    public partial class MasterMenu : BaseEntity
    {
        [DisplayName("Id")]
        public int MasterMenuId { get; set; }
        [MaxLength(250)]
        [MinLength(2)]
        [Required(ErrorMessage = "Name Is Required")]
        [DisplayName("Name")]
        public string MasterMenuName { get; set; }
        [Required(ErrorMessage = "Url Is Required")]
        [DisplayName("Url")]
        public string MasterMenuUrl { get; set; }
    }
}

Sakanatcom/ViewModels/MasterMenuViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Sakanatcom.ViewModels
{
    public class MasterMenuViewModel : BaseEntity
    {
        [DisplayName("Id")]
        public int MasterMenuId { get; set; }
        [MaxLength(250)]
        [MinLength(2)]
        [Required(ErrorMessage = "Name Is Required")]
        [DisplayName("Name")]
        public string MasterMenuName { get; set; }
        [Required(ErrorMessage = "Url Is Required")]
        [DisplayName("Url")]
        public string MasterMenuUrl { get; set; }
    }
}

Sakanatcom/Areas/Admin/Controllers/MasterMenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sakanatcom.Models;
using Sakanatcom.Models.Repositories;
using Sakanatcom.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Sakanatcom.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MasterMenuController : Controller
    {
        public IRepository<MasterMenu> MasterMenuRepository { get; }

        public MasterMenuController(IRepository<MasterMenu> MasterMenuRepository)
        {
            this.MasterMenuRepository = MasterMenuRepository;
        }
        public ActionResult Index()
        {
            IList<MasterMenu> dataList = MasterMenuRepository.View();
            IList<MasterMenuViewModel> dataViewModelList = new List<MasterMenuViewModel>();
            foreach (var data in dataList)
            {
                MasterMenuViewModel dataViewModel = new MasterMenuViewModel()
                {
                    MasterMenuId = data.MasterMenuId,
                    MasterMenuName = data.MasterMenuName,
                    MasterMenuUrl = data.MasterMenuUrl,
                    IsActive = data.IsActive
                };
                dataViewModelList.Add(dataViewModel);
            }
            return View(dataViewModelList);
        }

        public ActionResult Active(int id)
        {
            MasterMenuRepository.Active(id, new MasterMenu()
            {
                EditDate = DateTime.UtcNow,
                EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier)
            });
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Create()
        {
            MasterMenuViewModel dataViewModel = new MasterMenuViewModel();
            return View(dataViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterMenuViewModel dataViewModel)
        {
            try
            {
                if (MasterMenuRepository.View().Where(data => data.MasterMenuName.ToUpper()
                == dataViewModel.MasterMenuName.ToUpper()).ToList().Count > 0)
                {
                    ModelState.AddModelError("", "This name is already used.");
                    return View(dataViewModel);
                }
                MasterMenu data = new MasterMenu()
                {
                    MasterMenuName = dataViewModel.MasterMenuName,
                    MasterMenuUrl = dataViewModel.MasterMenuUrl,
                    CreateDate = DateTime.UtcNow,
                    CreateUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    IsActive = true,
                    IsDelete = false
                };
                MasterMenuRepository.Add(data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            MasterMenu data = MasterMenuRepository.Find(id);
            MasterMenuViewModel dataViewModel = new MasterMenuViewModel()
            {
                MasterMenuId = data.MasterMenuId,
                MasterMenuName = data.MasterMenuName,
                MasterMenuUrl = data.MasterMenuUrl
            };
            return View(dataViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MasterMenuViewModel dataViewModel)
        {
            try
            {
                MasterMenu data = MasterMenuRepository.Find(id);
                if (MasterMenuRepository.View().Where(data => data.MasterMenuName.ToUpper()
                == dataViewModel.MasterMenuName.ToUpper()).ToList().Count > 0
                && data.MasterMenuName.ToUpper() != dataViewModel.MasterMenuName.ToUpper())
                {
                    ModelState.AddModelError("", "This name is already used.");
                    return View(dataViewModel);
                }
                data.MasterMenuName = dataViewModel.MasterMenuName;
                data.MasterMenuUrl = dataViewModel.MasterMenuUrl;
                data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                data.EditDate = DateTime.UtcNow;
                MasterMenuRepository.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            MasterMenuRepository.Delete(id, new MasterMenu()
            {
                EditDate = DateTime.UtcNow,
                EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier)
            });
            return RedirectToAction(nameof(Index));
        }
    }
}

Sakanatcom/Areas/Admin/Views/MasterMenu/Create.cshtml
@model Sakanatcom.ViewModels.MasterMenuViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterMenu">Menu</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form asp-action="Create">
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterMenuId" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterMenuId" readonly class="form-control" />
                                        <span asp-validation-for="MasterMenuId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterMenuName" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterMenuName" class="form-control" />
                                        <span asp-validation-for="MasterMenuName" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterMenuUrl" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterMenuUrl" class="form-control" />
                                        <span asp-validation-for="MasterMenuUrl" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 d-inline-flex justify-content-end">
                                <a asp-action="Index" class="btn btn-success btn-backtolist">Back to List</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Sakanatcom/Areas/Admin/Views/MasterMenu/Edit.cshtml
@model Sakanatcom.ViewModels.MasterMenuViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterMenu">Menu</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form asp-action="Edit">
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterMenuId" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterMenuId" readonly class="form-control" />
                                        <span asp-validation-for="MasterMenuId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterMenuName" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterMenuName" class="form-control" />
                                        <span asp-validation-for="MasterMenuName" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <div class="row mb-3">
                                    <label asp-for="MasterMenuUrl" class="col-sm-4 col-form-label"></label>
                                    <div class="col-sm-8">
                                        <input asp-for="MasterMenuUrl" class="form-control" />
                                        <span asp-validation-for="MasterMenuUrl" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 d-inline-flex justify-content-end">
                                <a asp-action="Index" class="btn btn-success btn-backtolist">Back to List</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Sakanatcom/Areas/Admin/Views/MasterMenu/Index.cshtml
@model IEnumerable<Sakanatcom.ViewModels.MasterMenuViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">Menu</li>
        </ol>
    </nav>
</div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-end">
                        <a asp-action="Create" class="btn btn-primary">Create New +</a>
                    </h5>
                    <table class="table datatable index-table text-break">
                        <thead>
                            <tr class="bg-dark text-white">
                                <th>
                                    @Html.DisplayNameFor(model => model.MasterMenuId)
                                </th>
                                <th class="w-25">
                                    @Html.DisplayNameFor(model => model.MasterMenuName)
                                </th>
                                <th class="w-25">
                                    @Html.DisplayNameFor(model => model.MasterMenuUrl)
                                </th>
                                <th class="text-center">
                                    Operations
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-dark-light">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="align-middle">
                                        @Html.DisplayFor(modelItem => item.MasterMenuId)
                                    </td>
                                    <td class="align-middle w-25">
                                        @Html.DisplayFor(modelItem => item.MasterMenuName)
                                    </td>
                                    <td class="align-middle w-25">
                                        @Html.DisplayFor(modelItem => item.MasterMenuUrl)
                                    </td>
                                    <td class="align-middle text-center">
                                        <a asp-action="Edit" asp-route-id="@item.MasterMenuId">
                                            <i class="bx bxs-edit text-secondary h5"></i>
                                        </a>
                                        <a href="" data-bs-toggle="modal" data-bs-target="#deleteModal" id="btn-delete"
                                       data-path="@Url.ActionLink("Delete","MasterMenu",new {id= item.MasterMenuId})">
                                            <i class="bx bxs-trash text-danger h5"></i>
                                        </a>
                                        @if (item.IsActive)
                                        {
                                            <a asp-action="Active" asp-route-id="@item.MasterMenuId">
                                                <i class="ri-eye-fill text-success h5"></i>
                                            </a>
                                        }
                                        else
                                        {
                                            <a asp-action="Active" asp-route-id="@item.MasterMenuId">
                                                <i class="ri-eye-close-fill text-danger h5"></i>
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>